internet_shop/cart/urls.py
from django.urls import path, include
from cart.views import *

urlpatterns = [
    path('', cart_page, name='cart'),
    path('cart_dell_product/<int:id>', cart_dell_product, name='cart_dell_product'),

]

internet_shop/internet_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('user/', include('user_and_customer.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order_and_pay.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

internet_shop/main/urls.py
from django.urls import path, include
from main.views import *

urlpatterns = [
    path('', global_categories, name='main_page'),
    path('category/', global_categories, name='global_categories'),
    path('category/<slug>', category, name='category'),
    path('product/<int:pk>', product_card, name='product_card'),
    path('contacts/', contacts, name='contacts'),
    path('wish/', wish, name='wish'),
    path('delivery_terms/', delivery_terms, name='delivery_terms'),
]

internet_shop/main/models.py
from django.db import models
from django.urls import reverse
from utils.utils import resize_photo

_MAX_PHOTO_SIZE = 800


class Category(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=150, verbose_name='Название категории')
    slug = models.SlugField(max_length=150, unique=True, verbose_name='Слаг')
    parent_category = models.ForeignKey('self', on_delete=models.CASCADE, verbose_name='Родительская категория', blank=True, null=True)
    photo = models.ImageField(upload_to='category_photos/', verbose_name='Фото', blank=True)
    is_published = models.BooleanField(default=True, verbose_name='Публикация')
    views = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        if self.parent_category:
            return self.parent_category.__str__() + " --> " + self.title

        return self.title

    def save(self, *args, **kwargs):
        """
        Меняем разрешение картинки на меньшее, если оно больше максимального размера в пикселях.
        """
        super(Category, self).save(*args, **kwargs)
        if self.photo is None:
            self.photo = "no_photo.png"

        resize_photo(self.photo, _MAX_PHOTO_SIZE)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ['title']


class Product(models.Model):

    CHOICES_UNIT = [
        ('piece', 'штуку'),
        ('kilogram', 'килограмм'),
        ('gram', 'грамм'),
        ('centimeter', 'сантиметр'),
        ('meter', 'метр'),
    ]

    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=150, verbose_name='Название')
    article = models.IntegerField(verbose_name='Артикул', unique=True)
    description = models.TextField(verbose_name='Описание', blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    main_image = models.ImageField(verbose_name='Главное изображение', upload_to='product_photo/', blank=True)
    price_unit = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена за штуку')
    unit_of_measurement = models.CharField(max_length=200,
                                           choices=CHOICES_UNIT, default='piece',
                                           verbose_name='Единица измерения')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')
    update_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    is_published = models.BooleanField(default=True, verbose_name='Публикация')
    in_stock = models.BooleanField(default=True, verbose_name='В наличии')
    views = models.IntegerField(default=0, verbose_name='Кол-во просмотров')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_card', kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        """
        Меняем разрешение картинки на меньшее, если оно больше максимального размера в пикселях.
        """
        super(Product, self).save(*args, **kwargs)
        resize_photo(self.main_image, _MAX_PHOTO_SIZE)

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ['-views']


class ImageGallery(models.Model):
    id = models.AutoField(primary_key=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    additional_picture = models.ImageField(verbose_name='Дополнительное изображение', upload_to='product_photo/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')

    def __str__(self):
        return self.product.title

    def save(self, *args, **kwargs):
        """
        Меняем разрешение картинки на меньшее, если оно больше максимального размера в пикселях.
        """
        super(ImageGallery, self).save(*args, **kwargs)
        resize_photo(self.additional_picture, _MAX_PHOTO_SIZE)

    class Meta:
        verbose_name = "Дополнительное изображение"
        verbose_name_plural = "Дополнительные изображения"
        ordering = ['-created_at']


class Wish(models.Model):
    CHOICES_STATUS = [
        ('wish_is_made', 'Создано'),
        ('wish_is_done', 'Выполнено'),
        ('wish_is_fulfilled', 'Отклонено'),
    ]

    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=150, verbose_name='Краткое описание')
    name = models.CharField(max_length=150, verbose_name='Имя')
    contacts = models.CharField(max_length=150, verbose_name='Адрес электронной почты либо телефон', blank=True)
    description = models.TextField(verbose_name='Подробное описание', blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    status = models.CharField(max_length=200, choices=CHOICES_STATUS, default='wish_is_made', verbose_name='Статус')

    class Meta:
        verbose_name = "Пожелание"
        verbose_name_plural = "Пожелания"
        ordering = ['-created_at']


class SiteSettings(models.Model):
    id = models.AutoField(primary_key=True)
    key_title = models.CharField(max_length=150, verbose_name='Ключ')
    description = models.CharField(max_length=150, verbose_name='Описание')
    value = models.TextField(verbose_name='Значение')

    class Meta:
        verbose_name = "Настройка сайта"
        verbose_name_plural = "Настройки сайта"

internet_shop/main/forms.py
from django import forms
from main.models import Wish


class WishForm(forms.ModelForm):
    name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class': 'form_field'}))
    title = forms.CharField(label='Краткое описание', widget=forms.TextInput(attrs={'class': 'form_field'}))
    contacts = forms.CharField(label='Адрес электронной почты либо телефон', widget=forms.TextInput(attrs={'class': 'form_field'}))
    description = forms.CharField(label='Подробное описание', widget=forms.Textarea(attrs={'class': 'form_field', 'rows': 5}))

    class Meta:
        model = Wish
        fields = ('name', 'contacts', 'title', 'description',)

internet_shop/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from main.models import Category, Product, SiteSettings
from django.db.models import Count, F
from django.core.paginator import Paginator
from cart.cart import Cart
from cart.forms import CartAddProductForm
from main.forms import WishForm
from django.urls import reverse_lazy


def main_page(request):
    products = Product.objects.order_by('-views')[:4]
    context = {'products': products}
    return render(request, 'main/main_page.html', context)


def global_categories(request):
    all_global_categories = Category.objects.filter(parent_category=None)
    context = {'all_categories': all_global_categories}
    return render(request, 'main/global_categories.html', context)


def global_category(request, slug):
    global_category = Category.objects.filter(parent_category=None).get(slug=slug)
    all_categories = Category.objects.filter(global_category=global_category, is_published=True)
    context = {'all_categories': all_categories, 'global_category': global_category}
    return render(request, 'main/categories.html', context)


def category(request, slug):
    category = Category.objects.get(slug=slug)
    all_products = Product.objects.filter(category=category, is_published=True)
    child_categories = Category.objects.filter(parent_category=category)

    form_cart = CartAddProductForm()

    # счетчик посещений этой категории
    if request.GET.get('page') is None:
        category.views = F('views') + 1
    category.save()

    # пагинация
    paginator = Paginator(all_products, 20)
    page_num = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_num)

    # добавление товаров в корзину
    if request.method == "POST":
        cart = Cart(request)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            product = Product.objects.get(id=form.cleaned_data['id_product'])
            cart.add(product=product, quantity=form.cleaned_data['quantity'])

    context = {
        'category': category,
        'page_obj': page_obj,
        'form_cart': form_cart,
        'child_categories': child_categories,
        'breadcrumbs': _get_breadcrumbs(category)
    }

    return render(request, 'main/category.html', context)


def _get_breadcrumbs(cat):
    breadcrumbs = []
    while cat.parent_category is not None:
        breadcrumbs.insert(0, cat.parent_category)
        cat = cat.parent_category

    return breadcrumbs



def product_card(request, pk):
    product = Product.objects.get(pk=pk)
    additional_pictures = product.imagegallery_set.all()
    form_cart = CartAddProductForm()
    product.views = F('views') + 1
    product.save()
    context = {'product': product, 'additional_pictures': additional_pictures, 'form_cart': form_cart}

    if request.method == "POST":
        cart = Cart(request)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            cart.add(product=product, quantity=form.cleaned_data['quantity'])

    return render(request, 'main/product_card.html', context)


def contacts(request):
    return render(request, 'main/contacts.html')


def wish(request):
    if request.method == "POST":
        form = WishForm(request.POST)
        if form.is_valid():
            form.save()
        header = 'Благодарим за пожелания'
        context = {'header': header}
    else:
        header = 'Ваши пожелания'
        form = WishForm()
        context = {'form': form, 'header': header}

    return render(request, 'main/wish.html', context)


def delivery_terms(request):
    settings_delivery_terms = SiteSettings.objects.get(id=2)  # забираем текст из модели настроек
    text = settings_delivery_terms.value
    context = {'text': text}
    return render(request, 'main/delivery_terms.html', context)

internet_shop/main/templates/main/categories.html
{% extends "base.html" %}

{% block title %} Категории {% endblock %}

{% load static %}
{% block for_connect_another %}<link rel="stylesheet" href="{% static 'main/css/categories.css' %}">{% endblock%}

{% block content %} 

<br>
<div class="navigation">
  <a href="{% url 'global_categories' %}">Главная</a> >
  <p>{{ global_category }}</p>
</div>

<h2 class="title">{{ global_category }}</h2>

<div class="col-xs-12">
    <div class="categories">
        <div class="hidden-xs hidden-sm hidden-md col-lg-3">
            <div class="left_block">
                {% for category in all_categories %}
                <div class="categories_category">
                    <a href="/category/{{ category.slug }}">
                        <div><img src="{{ category.photo.url }}" alt=""></div>
                        <div class="categories_title">{{category.title}}</div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-9">
            <div class="right_block">
                {% for category in all_categories %}
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-4">
                    <div class="categories_category">
                        <a href="/category/{{ category.slug }}">
                            <div><img src="{{ category.photo.url }}" alt=""></div>
                            <div class="categories_title">{{category.title}}</div>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>








<!-- <h2>{{ global_category }}</h2>
<br>

<div class="categories_categories">
    
  {% for category in all_categories %}
    
    <div class="categories_category">
        <a href="/category/{{ category.slug }}">
        <div>
            <img src="{{ category.photo.url }}" alt="">
        </div>
        <div class="categories_title">{{category.title}}</div>
        </a>
    </div>

  {% endfor %}

</div> -->


{% endblock%}

internet_shop/main/templates/main/category.html
{% extends "base.html" %}

{% block title %} {{category.title}} {% endblock %}

{% load static %}
{% block for_connect_another %}<link rel="stylesheet" href="{% static 'main/css/caregory_v1.css' %}">{% endblock%}

{% block content %} 

<br>
<div class="navigation">
  <a href="{% url 'global_categories' %}">Главная</a> >
    {% for parent_category in breadcrumbs %}
        <a href="/category/{{ parent_category.slug }}">{{ parent_category.title }}</a> >
    {% endfor %}
  <p>{{category.title}}</p>
</div>


<div class="category_title">
    <h2 class="title">{{category.title}}</h2>
</div>

{% if child_categories %}
<h3 class="title">Подкатегории</h3>
<div class="child_categories">
    {% for child_category in child_categories %}
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-4">
            <div class="child_category">
                <a href="/category/{{ child_category.slug }}">
                    <div>
                        <img src="{{ child_category.photo.url }}" alt="">
                    </div>
                    <div class="child_category_title">{{child_category.title}}</div>
                </a>
            </div>
        </div>
    {% endfor %}
</div>
{% endif %}

{% if page_obj %}

<h3 class="title">Товары</h3>

<div class="category_products">
    {% for product in page_obj %}
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-3">
          <div class="category_product">
              <div class="articl">Артикул: {{ product.article }}</div>
              <a href="{{ product.get_absolute_url }}">
                  <div class="product_img"><img src="{{ product.main_image.url }}" alt=""></div>
                  <div class="product_title"><b>{{product.title}}</b></div>
              </a>
              <br>
              {% if product.in_stock %}
                <div class="prices">
                    <div><b>Цена за {{ product.get_unit_of_measurement_display }}: {{ product.price_unit }}</b></div>
                </div>
                  
                <div class="cart">
                  <div class="batton_and_quantity">
                    <button id="minus_{{ product.id }}">-</button>
                    <div id="col_{{ product.id }}"><b>1</b></div>
                    <button id="plus_{{ product.id }}">+</button>
                  </div>
                  
                  <form method="POST" class="cart_form">
                    {% csrf_token %}
                    <input type="hidden" name="id_product" value="{{product.id}}">
                    <input id="quantity_{{ product.id }}" type="hidden" name="quantity" class="cart_quantity" value="1">
                    <button type="submit" class="button"> <b>Добавить в корзину</b></button>
                  </form>

                  <script type="text/javascript">
                    $('#plus_{{ product.id }}').on('click', function () {
                        let num = +$('#quantity_{{ product.id }}').val();
                        $('#col_{{ product.id }}').text(num + 1);
                        $('#quantity_{{ product.id }}').val(num + 1);
                    });
                    $('#minus_{{ product.id }}').on('click', function () {
                        let num = +$('#quantity_{{ product.id }}').val();
                        if (num > 1) $('#col_{{ product.id }}').text(num - 1);
                        if (num > 1) $('#quantity_{{ product.id }}').val(num - 1);
                    });
                  </script>
                </div>

              {% else %}
                <div><b>Товар отсутвует на складе.</b></div>
                <br>
                <div>Для заказа необходимо связаться с менеджером по номеру телефона: {{ contacts_for_order }}</div>
              {% endif %} 
          </div>  
        </div>       
    {% endfor %} 
</div>
{% endif %}




<div>
    
</div>

<div class="paginator">
  <div class="paginator_back">
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}"><</a>
    {% endif %}
  </div>
  
  <div class="paginator_number">
    {% if page_obj.has_next %}
      {% for i in page_obj.paginator.page_range %}
        {% if i == page_obj.number %}  
          <a href="?page={{ i }}" class="number_page page_active">{{ i }}</a>
        {% elif i > page_obj.number|add:-3 and i < page_obj.number|add:3 %}
          <a href="?page={{ i }}" class="number_page">{{ i }}</a>
        {% endif %}
      {% endfor %}
    {% endif %}
  </div>

  <div class="paginator_next">
    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">></a>
    {% endif %}
  </div>
</div>



{% endblock%}

internet_shop/main/templates/main/contacts.html
{% extends "base.html" %}

{% block title %} Контакты {% endblock %}

{% load static %}
{% block for_connect_another %}<link rel="stylesheet" href="{% static 'main/css/contacts.css' %}">{% endblock%}

{% block content %} 

<h2 class="title">Контакты</h2>
<div class="contacts2">
    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-4">
        <div class="descriprion">
            <div class="contacts_raw">
                <img src="{% static 'img/clock.png' %}" alt="">
                <p><b>{{ contacts_time }}</b></p>
            </div>
            <div class="contacts_raw">
                <img src="{% static 'img/phone.png' %}" alt="">
                <p><b>{{ contacts_telephone }}</b></p>
            </div>
            <div class="contacts_raw">
                <img src="{% static 'img/mail.png' %}" alt="">
                <p><b>{{ contacts_email }}</b></p>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-9 col-lg-8">
        <div class="map">
            <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Aadf3651ac555cfc084b7851a6ccda26ba80b19b3b5a4ce5c40c651e933ac7f1f&amp;width=619&amp;height=486&amp;lang=ru_RU&amp;scroll=true"></script>
        </div>
    </div>
</div>

{% endblock%}

internet_shop/main/templates/main/delivery_terms.html
{% extends "base.html" %}

{% block title %} Условия доставки {% endblock %}

{% load static %}

{% block for_connect_another %}
    <link rel="stylesheet" href="{% static 'main/css/delivery_terms.css' %}">
        
{% endblock%}

{% block content %} 

<h2 class="title">Условия доставки</h2>

{% autoescape off %}
    {{ text }}
{% endautoescape %}

{% endblock%}

internet_shop/main/templates/main/global_categories.html
{% extends "base.html" %}

{% block title %} Категории {% endblock %}

{% load static %}
{% block for_connect_another %}<link rel="stylesheet" href="{% static 'main/css/global_categories_v1.css' %}">{% endblock%}

{% block content %} 

<br>
<div class="navigation">
  <a href="{% url 'global_categories' %}">Главная</a> >
</div>

<h2 class="title">Категории товаров</h2>

<div class="col-xs-12">
    <div class="global_categories">
        <div class="hidden-xs hidden-sm hidden-md col-lg-3">
            <div class="left_block">
                {% for category in all_categories %}
                <div class="global_categories_category">
                    <a href="/category/{{ category.slug }}">
                        <div><img src="{{ category.photo.url }}" alt=""></div>
                        <div class="categories_title">{{category.title}}</div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-9">
            <div class="right_block">
                {% for category in all_categories %}
                <div class="col-xs-6 col-sm-6 col-md-6 col-lg-4">
                    <div class="global_categories_category">
                        <a href="/category/{{ category.slug }}">
                            <div><img src="{{ category.photo.url }}" alt=""></div>
                            <div class="categories_title">{{category.title}}</div>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock%}

internet_shop/main/templates/main/main_page.html
{% extends "base.html" %}

{% block title %} Главная {% endblock %}

{% load static %}
{% block for_connect_another %}<link rel="stylesheet" href="{% static 'main/css/main_page.css' %}">{% endblock%}


{% block content %} 

<h4 class="title">4 самых популярных товара:</h4>

<div class="main_products">
    {% for product in products %}
        
        <div class="main_product">

            <div class="article">Артикул: {{ product.article }}</div>
            <a href="/product/{{ product.pk }}">
                <div class="product_img"><img src="{{ product.main_image.url }}" alt=""></div>
                <div class="product_title">{{product.title}}</div>
            </a>
            
            <br>
            <div class="prices">
                <div>Цена за штуку: {{ product.price_unit }}</div>
                <div>Цена за упаковку: {{ product.price_pack }}</div>
            </div>

            <br>

        </div>

    {% endfor %} 
</div>


{% endblock%}

    

internet_shop/main/templates/main/product_card.html
{% extends "base.html" %}

{% block title %} {{product.title}} {% endblock %}

{% load static %}

{% block for_connect_another %}<link rel="stylesheet" href="{% static 'main/css/product_card_v2.css' %}">{% endblock%}


{% block content %} 

<br>
<div class="navigation">
  <a href="{% url 'global_categories' %}">Главная</a> >
  <a href="/global_category/{{ product.category.global_category.slug }}">{{ product.category.global_category }}</a> >
  <a href="/category/{{ product.category.slug }}">{{ product.category }}</a>
</div>


<div class="product_card">

    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
        <div class="pictures">
            <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
                <div class="main_picture">
                    <img src="{{ product.main_image.url }}" alt="">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <div class="additional_pictures">
                        <a href="{{ product.main_image.url }}"><img src="{{ product.main_image.url }}" alt=""></a>
                    {% for i in additional_pictures %}
                        <a href="{{ i.additional_picture.url }}"><img src="{{ i.additional_picture.url }}" alt=""></a>
                    {% endfor %}
                </div> 
            </div>
            
            <script type="text/javascript">
                $(document).ready(function(){
                    $(".additional_pictures a").click(function(){
                        var largePath = $(this).attr("href");

                        $(".main_picture img").attr({ src: largePath, });
                        return false;
                    });
                });
            </script>

        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <div class="product_title_and_description">
            <div class="product_title"> <b>{{product.title}}</b></div>
            <div class="articl">Артикул: {{product.article}}</div>
            <br>
            {% if product.description %}
            <br>
            <div><b>Описание:</b> {{product.description}}</div>
            <br>
            <br>
            {% endif %}
            <br>
            {% if product.in_stock %}
            <div class="cart">
                <div class="price"><b>Цена за {{ product.get_unit_of_measurement_display }}: {{product.price_unit}}</b></div>
                <div class="batton_and_quantity">
                    <button id="minus_{{ product.id }}">-</button>
                    <div id="col_{{ product.id }}"><b>1</b></div>
                    <button id="plus_{{ product.id }}">+</button>
                </div>
                
                <form method="POST" class="cart_form">
                    {% csrf_token %}
                    <input type="hidden" name="id_product" value="{{product.id}}">
                    <input id="quantity_{{ product.id }}" type="hidden" name="quantity" class="cart_quantity" value="1">
                    <button type="submit" class="button"> <b>Добавить в корзину</b></button>
                </form>

                <script type="text/javascript">
                    $('#plus_{{ product.id }}').on('click', function () {
                        let num = +$('#quantity_{{ product.id }}').val();
                        $('#col_{{ product.id }}').text(num + 1);
                        $('#quantity_{{ product.id }}').val(num + 1);
                    });
                    $('#minus_{{ product.id }}').on('click', function () {
                        let num = +$('#quantity_{{ product.id }}').val();
                        if (num > 1) $('#col_{{ product.id }}').text(num - 1);
                        if (num > 1) $('#quantity_{{ product.id }}').val(num - 1);
                    });
                </script>
            </div>
            {% else %}
            <p><b>Товар отсутвует на складе.</b></p>
            <p>Для заказа необходимо связаться с менеджером по номеру телефона: {{ contacts_for_order }}</p>
            {% endif %}

        </div>
    </div>

    
</div>


{% endblock%}

internet_shop/main/templates/main/wish.html
{% extends "base.html" %}

{% block title %} {{product.title}} {% endblock %}

{% load static %}

{% block for_connect_another %}<link rel="stylesheet" href="{% static 'main/css/wish.css' %}">{% endblock%}


{% block content %} 


<div class="wish">
    <h2 class="title">{{header}}</h2>
    {% if form %}
        <h3>Пожалуйста, заполните форму</h3>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4">
            <form method="POST" class="wish_form">
                {% csrf_token %}
                {% for item in form %}
                    <div class="wish_form_field">
                        <div>{{item.label_tag}}</div>
                        <div>{{item}}</div>
                    </div>
                {% endfor %}
                <br>
                <button type="submit" class="button_make_wish">Отправить отзыв</button>
            </form>
        </div>
    {% endif %}
</div>


{% endblock%}